# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TomTomLocatorFilter
                                 A QGIS plugin
 This is a plugin which adds a TomTom Locator Filter (Geocoder) to QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-01
        copyright            : (C) 2020 by Eduin Carrillo
        email                : yecarrillo@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TomTomLocatorFilter class from file TomTomLocatorFilter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tomtomfilter import TomTomFilterPlugin
    return TomTomFilterPlugin(iface)
